Repository schedule-Avengers/taskify, pull requests merged in 2024-05, with the labels that each got.

#13 develop --> main 머지
  .github/workflows/deploy.yml
  src/types/types.ts
Labels: feat

#27 공용 모달 컴포넌트 추가
  index.html
  src/common/Modal.module.scss
  src/common/Modal.tsx
Labels: design, chore

#25 공용 버튼 컴포넌트 추가
  package-lock.json
  package.json
  src/components/common/BaseButton.module.scss
  src/components/common/BaseButton.tsx
  src/image/ic_invite.svg
Labels: design, chore

#32 1rem = 10px 로 변경 및 px --> rem 으로 변경
  src/components/common/BaseButton.module.scss
  src/components/common/Modal.module.scss
  src/components/common/Modal.tsx
  src/main.css
  src/main.tsx
Labels: refactor

#38 Feat/hyun/34
  src/font/Pretendard-woff/Pretendard-Black.woff
  src/font/Pretendard-woff/Pretendard-Bold.woff
  src/font/Pretendard-woff/Pretendard-ExtraBold.woff
  src/font/Pretendard-woff/Pretendard-ExtraLight.woff
  src/font/Pretendard-woff/Pretendard-Light.woff
  src/font/Pretendard-woff/Pretendard-Medium.woff
  src/font/Pretendard-woff/Pretendard-Regular.woff
  src/font/Pretendard-woff/Pretendard-SemiBold.woff
  src/font/Pretendard-woff/Pretendard-Thin.woff
  src/styles/global.module.scss
  src/styles/global.scss
  src/styles/mixin.scss
  src/styles/variable.scss
Labels: chore
