Repository schedule-Avengers/taskify, pull requests merged in 2024-07, with the labels that each got.

#43 mypage UI 작업
  package-lock.json
  package.json
  src/App.tsx
  src/components/MyPage/PasswordChangeForm.module.scss
  src/components/MyPage/PasswordChangeForm.tsx
  src/components/MyPage/ProfileForm.module.scss
  src/components/MyPage/ProfileForm.tsx
  src/components/common/BaseButton/baseButton.module.scss
  src/components/common/BaseButton/index.tsx
  src/components/common/SideBar/SideBar.module.scss
  src/components/common/SideBar/index.tsx
  src/components/dashboard/Card.module.scss
  src/components/dashboard/DashBoardDetail.module.scss
  src/image/ic_add_withoutbackgound.svg
  src/image/ic_arrow_left.svg
  src/image/ic_redx.svg
  src/pages/Layout.module.scss
  src/pages/MyPage/MyPage.module.scss
  src/pages/MyPage/index.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/mypage.modul.scss
  src/styles/_variable.scss
Labels: feat, design

#44 로그인 로그아웃 UI 구현 API 연결
  src/axios/api.ts
  src/axios/axios.ts
  src/components/common/BaseButton/index.tsx
  src/components/common/Modal/index.tsx
  src/hooks/validationSchema.tsx
  src/pages/signin/index.tsx
  src/pages/signin/signin.module.scss
  src/pages/signup/index.tsx
  src/pages/signup/signup.module.scss
  src/types/types.ts
Labels: feat, design

#51 mypage 프로필 이미지 및 닉네임 변경 api 연결
  src/api/mypage/index.ts
  src/components/MyPage/ProfileForm.tsx
  src/hooks/mypage/useMyPage.ts
  src/pages/MyPage/MyPage.module.scss
  src/pages/MyPage/index.tsx
  src/types/types.ts
Labels: feat

#53 로그인 회원가입 반응형 및 유효성 검사 에러 해결
  src/components/common/BaseButton/baseButton.module.scss
  src/components/common/Input/AuthInput/authInput.module.scss
  src/components/common/Input/AuthInput/index.tsx
  src/pages/signin/index.tsx
  src/pages/signin/signin.module.scss
  src/pages/signup/index.tsx
  src/pages/signup/signup.module.scss
Labels: fix, design
